<?php
/** VARIÁVEL 'TRACE_LOG_EXT' SE FOR PASSADA DE UM ARQUIVO EXTERNO, O TRACE DE LOG SERÁ O NÍVEL INFORMADO NESTA VARIÁVEL
* PARA PASSAR ESTA VARIÁVEL DE UM ARQUIVO EXTERNO, O USUÁRIO SÓ PRECISA DEFINÍ-LA ANTES DE CHAMAR ESTE SCRIPT
* */
if($TRACE_LOG_EXT != ""){
	$CONFIG_LOG = $TRACE_LOG_EXT;
}else{
	$CONFIG_LOG = "TRACE";
}


/** NÍVEIS DE LOG: NÃO É NECESSÁRIO ALTERAR!
* O NÍVEL VAI DEPENDER DA DEFINIÇÃO DA VARIÁVEL 'CONFIG_LOG'
* POR EXEMPLO: INFO registra informações para INFO, WARNING, ERROR E FATAL
* OUTRO EXEMPLO: WARNING registra informações para WARNING, ERROR E FATAL
* */
define("LOG_LEVEL_ALL", false);
define("LOG_LEVEL_FATAL", ($CONFIG_LOG == "FATAL" || $CONFIG_LOG == "ERROR" || $CONFIG_LOG == "WARNING" || $CONFIG_LOG == "INFO" || $CONFIG_LOG == "TRACE"));
define("LOG_LEVEL_ERROR", ($CONFIG_LOG == "ERROR" || $CONFIG_LOG == "WARNING" || $CONFIG_LOG == "INFO" || $CONFIG_LOG == "TRACE"));
define("LOG_LEVEL_WARNING", ($CONFIG_LOG == "WARNING" || $CONFIG_LOG == "INFO" || $CONFIG_LOG == "TRACE"));
define("LOG_LEVEL_INFO", ($CONFIG_LOG == "INFO" || $CONFIG_LOG == "TRACE"));
define("LOG_LEVEL_TRACE", ($CONFIG_LOG == "TRACE"));
//define("LOG_LEVEL_SQL_TRACE", false);


/** EM QUANTOS DIAS OS LOGS ANTIGOS SERÃO EXCLUÍDO */
define("LOG_APAGA_PERIODO", 30);

/** DIRETÓRIO ONDE OS ARQUIVOS DE LOG SE ENCONTRAM */
define("LOG_DIRECTORY", "log");

/** DEFINIÇÃO DO NOME PADRÃO DO ARQUIVO DE LOG */
define("LOG_NAME", LOG_DIRECTORY ."/fissm-log-". date("Ymd"). ".log");
?>